### ISSUE TITLE
Project Reference

### ISSUE THREAD

**Issue by fabianofrank** [fabianofrank/rails-icook#8]
- Working on this project: @fabianofrank

- [Project](https://github.com/users/fabianofrank/projects/2)

**Comment by mukhammadrizooff** [comment]
Hi @fabianofrank, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media4.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/>

Good luck! 🎉 

- [ ] [IMPORTANT] Please include the reason why you are working alone in the issue description!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
